### ISSUE TITLE
streamlit windows installer problem

### ISSUE THREAD

**Issue by educhicano** [MannLabs/alphapeptstats#135]
**Describe the bug**
Hi, I'm trying to install alphapeptstats via Windows installer, but after the installation it doesnt start properly.
The prompt windows suddenly closes and it shows the following message: " 'streamlit' is not recognized as an internal or external command, operable program or batch file "

**To Reproduce**
Without any previous install, try to install alphapeptstats with or without administrator permissions, for all users or current user.

**Version (please complete the following information):**
 - OS: win10 pro for workstations

**Comment by michaelsteidel86** [comment]
Exactly the same problem on my end on multiple different systems all with win10 installed..

**Comment by educhicano** [comment]
Same error detected in MacOS 13.2.1 Ventura. Attached a screenshot
<img width="569" alt="Captura de pantalla 2023-03-14 a las 14 23 46" src="https://user-images.githubusercontent.com/21240536/225014890-58cd24cb-5325-4ba5-8e76-768192a1e67d.png">

**Comment by elena-krismer** [comment]
Thanks for reporting the bug! I'm on it rightnow.
In the meantime, you can use the command line  to install alphapeptstats and access the GUI:

```bash
conda create -n alphastats python==3.8
conda activate alphastats
pip install alphastats
alphastats gui
```

**Comment by elena-krismer** [comment]
@educhicano @michaelsteidel86 The bug should be fixed for Windows and MacOS :)
