### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by michaelsteidel86** [MannLabs/alphapeptstats#143]
Hi,

when starting the GUI version 0.4.4 (Win10) the following error is displayed in the Import Data tab:
![image](https://user-images.githubusercontent.com/98491942/225246449-88fae604-7118-4cde-85a9-438ab3a1f00e.png)

Could you please help me finding a solution?
Thanks in advance
Michael

**Comment by elena-krismer** [comment]
Sorry for the inconvenience the windows installer is causing me quite some trouble.  It is fixed in the latest version.
