### ISSUE TITLE
can't install: Microsoft visual error message

### ISSUE THREAD

**Issue by JM-Bader** [MannLabs/alphapeptstats#158]
I have picked python 3.10.9 according to the recommendations of python versions. 
![grafik](https://user-images.githubusercontent.com/98888664/228946524-2d4bf32e-7cec-4ea3-b34f-ced83f1b101f.png)

Tries to install: 
![grafik](https://user-images.githubusercontent.com/98888664/228946596-8dc1d1b6-701a-4cc7-ba10-18a26b9ae8f2.png)

yields: 
Installing collected packages: iteration-utilities, gitdb, click, blinker, tzlocal, sparse, rich, pydeck, pandas, outdated, numba-stats, gitpython, sklearn-pandas, data-cache, altair, streamlit, pandas-flavor, batchglm, pingouin, diffxpy, swifter, alphastats
  Running setup.py install for iteration-utilities: started
  Running setup.py install for iteration-utilities: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?d178a769-29ae-46d3-a8e9-db7e70c8c998)  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_additional_recipes.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_classes.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_convenience.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_recipes.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_utils.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\__init__.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      running build_ext
      building 'iteration_utilities._iteration_utilities' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for iteration-utilities
  error: subprocess-exited-with-error
...
╰─> iteration-utilities

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

While actually, I have: 
![grafik](https://user-images.githubusercontent.com/98888664/228946798-94b45bed-6c58-455a-be25-65c4965486cc.png)

**Comment by JM-Bader** [comment]
FYI: I and chatGPT found a solution. 

- One has to additionally install this: 
![grafik](https://user-images.githubusercontent.com/98888664/229108081-68c18b6a-cf01-4843-8153-abb086c378fd.png)

- upon installation of the above, alphastats can still not be installed. One then has to do the following: 
![grafik](https://user-images.githubusercontent.com/98888664/229108298-fa80c90f-1327-48a4-8684-bf02ef57d943.png)

then it works in my hands

**Comment by elena-krismer** [comment]
Thanks for reporting this (and also providing the solution)!  I cannot fix this within the package (despite removing dependencies) as this is more related to Visual Studio and Windows. However, I will document this in case  someone else is running into this issue :)

**Comment by pokhf123** [comment]
"(base) PS C:\WINDOWS\system32> pip install alphastats
Collecting alphastats
  Obtaining dependency information for alphastats from https://files.pythonhosted.org/packages/e2/51/2d4cabc2ebd962ca751ea7f0f8f39f8b8aff5ba50cb3aa176b8082b5c262/alphastats-0.6.9-py3-none-any.whl.metadata
  Using cached alphastats-0.6.9-py3-none-any.whl.metadata (7.0 kB)
Collecting pandas==2.0.2 (from alphastats)
  Obtaining dependency information for pandas==2.0.2 from https://files.pythonhosted.org/packages/ee/fd/a3b5f229e5098e18cb058549f9c2842f407023adb47aa6b22b44b15988c6/pandas-2.0.2-cp311-cp311-win_amd64.whl.metadata
  Using cached pandas-2.0.2-cp311-cp311-win_amd64.whl.metadata (18 kB)
Collecting scikit-learn==1.2.2 (from alphastats)
  Obtaining dependency information for scikit-learn==1.2.2 from https://files.pythonhosted.org/packages/db/98/169b46a84b48f92df2b5e163fce75d471f4df933f8b3d925a61133210776/scikit_learn-1.2.2-cp311-cp311-win_amd64.whl.metadata
  Using cached scikit_learn-1.2.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting data-cache>=0.1.6 (from alphastats)
  Obtaining dependency information for data-cache>=0.1.6 from https://files.pythonhosted.org/packages/9e/53/923886d94dbddb15cf917b59bfc64e89de09dcb103532c8affd67bed6555/data_cache-0.1.6-py3-none-any.whl.metadata
  Using cached data_cache-0.1.6-py3-none-any.whl.metadata (7.5 kB)
Collecting plotly==5.15.0 (from alphastats)
  Obtaining dependency information for plotly==5.15.0 from https://files.pythonhosted.org/packages/a5/07/5bef9376c975ce23306d9217ab69ca94c07f2a3c90b17c03e3ae4db87170/plotly-5.15.0-py2.py3-none-any.whl.metadata
  Using cached plotly-5.15.0-py2.py3-none-any.whl.metadata (7.0 kB)
Collecting statsmodels==0.14.0 (from alphastats)
  Obtaining dependency information for statsmodels==0.14.0 from https://files.pythonhosted.org/packages/c5/87/dfb50b24913cf3164e1ffbc176d36cd8d4e68c673a239cbcf676192a4350/statsmodels-0.14.0-cp311-cp311-win_amd64.whl.metadata
  Using cached statsmodels-0.14.0-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Collecting sklearn-pandas==2.2.0 (from alphastats)
  Obtaining dependency information for sklearn-pandas==2.2.0 from https://files.pythonhosted.org/packages/30/71/ccd5222f731993dfc1a6d9e766a507f1859bda4930b9548e54c11c876baf/sklearn_pandas-2.2.0-py2.py3-none-any.whl.metadata
  Using cached sklearn_pandas-2.2.0-py2.py3-none-any.whl.metadata (445 bytes)
Collecting pingouin==0.5.3 (from alphastats)
  Obtaining dependency information for pingouin==0.5.3 from https://files.pythonhosted.org/packages/27/bd/ea43fb929d1f20f9059fd8539eab06f4e1a5325b59854a10c5d88f62e37e/pingouin-0.5.3-py3-none-any.whl.metadata
  Using cached pingouin-0.5.3-py3-none-any.whl.metadata (1.2 kB)
Collecting scipy==1.10.1 (from alphastats)
  Obtaining dependency information for scipy==1.10.1 from https://files.pythonhosted.org/packages/65/76/903324159e4a3566e518c558aeb21571d642f781d842d8dd0fd9c6b0645a/scipy-1.10.1-cp311-cp311-win_amd64.whl.metadata
  Using cached scipy-1.10.1-cp311-cp311-win_amd64.whl.metadata (58 kB)
Requirement already satisfied: tqdm>=4.64.0 in c:\programdata\anaconda3\lib\site-packages (from alphastats) (4.66.5)
Collecting diffxpy==0.7.4 (from alphastats)
  Obtaining dependency information for diffxpy==0.7.4 from https://files.pythonhosted.org/packages/0b/30/3c5cccd84bf1dd1c99ccc17f563a2e8bf42e87311234f20efb9e9fef14e5/diffxpy-0.7.4-py3-none-any.whl.metadata
  Using cached diffxpy-0.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting anndata==0.9.1 (from alphastats)
  Obtaining dependency information for anndata==0.9.1 from https://files.pythonhosted.org/packages/ef/3a/4611e83c2bfca85518535aad65efb15f68c2c7c0831054b3011e6fb9a90d/anndata-0.9.1-py3-none-any.whl.metadata
  Using cached anndata-0.9.1-py3-none-any.whl.metadata (4.6 kB)
Collecting umap-learn==0.5.3 (from alphastats)
  Using cached umap-learn-0.5.3.tar.gz (88 kB)
  Preparing metadata (setup.py) ... done
Collecting streamlit==1.22.0 (from alphastats)
  Obtaining dependency information for streamlit==1.22.0 from https://files.pythonhosted.org/packages/b1/26/2add66d2e2febd6b05efd48ce02fc2d979d805b844143f2fa9fd7e867ade/streamlit-1.22.0-py2.py3-none-any.whl.metadata
  Using cached streamlit-1.22.0-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting tables==3.7.0 (from alphastats)
  Using cached tables-3.7.0.tar.gz (8.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.23.5 (from alphastats)
  Obtaining dependency information for numpy==1.23.5 from https://files.pythonhosted.org/packages/19/0d/b8c34e4baf258d77a8592bdce45183e9a12874c167f5966c7dd467b74ea9/numpy-1.23.5-cp311-cp311-win_amd64.whl.metadata
  Using cached numpy-1.23.5-cp311-cp311-win_amd64.whl.metadata (2.3 kB)
Collecting numba==0.56.4 (from alphastats)
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\DELL\AppData\Local\Temp\pip-install-0g070y0b\numba_d364e5262d9040e889f606d217100323\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\DELL\AppData\Local\Temp\pip-install-0g070y0b\numba_d364e5262d9040e889f606d217100323\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.5; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details."
Hello, I have been having this error when installing, how should I modify it? In addition, from another way, I downloaded the windows version of the installation package, click alphastats_gui.exe can not open, is there any step I missed?

**Comment by JuliaS92** [comment]
Hi @pokhf123 we have not tested support for python 3.11 yet. You need to therefore run it with python 3.10 max.

**Comment by pokhf123** [comment]
thanks!

> Hi @pokhf123 we have not tested support for python 3.11 yet. You need to therefore run it with python 3.10 max.
