### ISSUE TITLE
Not able to input FragPipe Output data

### ISSUE THREAD

**Issue by BenSamy2020** [MannLabs/alphapeptstats#173]
Greetings,

**Describe the bug**
I am not able to input my FragPipe output data into your tool on your GUI. Please refer to screenshot of the error below.

![image](https://user-images.githubusercontent.com/69944967/232287091-a2dd539f-d223-4c65-a41d-de7581c12bac.png)

Regards,
Ben

**Comment by elena-krismer** [comment]
@BenSamy2020  Thanks a lot for reporting the bug! It is fixed in version 0.5.2 (should be available in ~30 minutes)

**Comment by BenSamy2020** [comment]
Greetings @elena-krismer,

After uploading the combined_protein.tsv file, I am not able to initiate data overview. I am providing you with my combined_protein.tsv file and sample label file for your testing. Please allow your tool to incorporate these MSFragger output file.

![image](https://user-images.githubusercontent.com/69944967/232768542-06b72295-0841-4eba-84e8-2b76b17666c5.png)
[Uploading.zip](https://github.com/MannLabs/alphapeptstats/files/11261374/Uploading.zip)

Regards,
Ben

**Comment by elena-krismer** [comment]
@BenSamy2020 thanks for reporting and providing the input file :). it is fixed in release 0.5.3
