### ISSUE TITLE
one-click Windows installer?

### ISSUE THREAD

**Issue by hcadre** [MannLabs/alphapeptstats#222]
In the readme file it says:
![image](https://github.com/MannLabs/alphapeptstats/assets/16349515/6b202a8d-1378-4dcc-8538-56974726a4dc)
However, when following the link the installers for Linux and MacOS are present but not the installer for Windows:
![image](https://github.com/MannLabs/alphapeptstats/assets/16349515/b232e579-f6b9-4da4-af24-c0f66f0b3ffe)
Could you please provide the missing installer as well?
Best,

**Comment by elena-krismer** [comment]
@hcadre I am very sorry for the late response! The Windows installer is fixed now and you can find it here: https://github.com/MannLabs/alphapeptstats/releases/tag/alphastats_0.6.4 :)
