### ISSUE TITLE
color from plot_sampledistribution

### ISSUE THREAD

**Issue by bolak92** [MannLabs/alphapeptstats#229]
**bug description**
the bug happens when using the function .plot_sampledistribution while selecting a column for coloring by values. the column from the metadata has two unique values "D" or "N" for Diseased and Normal cells.

the graph output is in Black and white, there are still two entities in the legend but they are both having grey color?

I assume that the color pallete is not activated somehow or wrongly referenced in this case, or I might be missing some dependencies.
I tried to reinstall plotly package within my conda, but the issue was reproduced.

**Screenshots**
![image](https://github.com/MannLabs/alphapeptstats/assets/49613273/7bd28755-1020-4ed9-ae82-ddd56819f325)

**Version:**
- OS: Windows 10
- Version: 0.6.3
- Installation Type: Python (within a conda env)

**Comment by bolak92** [comment]
Additionally, the for

**Comment by bolak92** [comment]
additionally the type of argument color, is incorrectly assigned within the code: 

def plot_sampledistribution(
        self, method: str = "violin", color: bool = None, log_scale: bool = False
    ):
    
I believe it should be str not bool. 
hope that helps.

**Comment by elena-krismer** [comment]
@bolak92 Thanks for reporting the issue and debugging it as well! :grin: 
The actual issue was, that the newer versions of plotly are not accepting the declared color palette as default.

**Comment by bolak92** [comment]
I think the same issue is reproduced with the function plot_correlation_matrix()
![image](https://github.com/MannLabs/alphapeptstats/assets/49613273/91991280-f58e-4889-afc9-1b59be684ef0)
