### ISSUE TITLE
Conversion of pd.DataFrame to a DataSet instance

### ISSUE THREAD

**Issue by llniu** [MannLabs/alphapeptstats#271]
Sometimes I need to use external tools for data processing, such as batch effect correction or normalization techniques that are not available in Alphapeptstats. However, the resulting data frame cannot be analyzed using the statistical methods provided by alphastats. 

Is there a way to convert a data frame to a DataSet instance?

**Comment by llniu** [comment]
I guess a work-around is to re-load the modified data frame into DataSet. That would require converting wide data format into long format, or whatever format that alphapeptstats accepts?

**Comment by JuliaS92** [comment]
Would you want to be able to do this in a notebook or through the GUI?
For the GUI you would need to export to csv and use the Generic input format.
From code you can use the [GenericLoader](https://github.com/MannLabs/alphapeptstats/blob/main/alphastats/loader/GenericLoader.py) directly, which accepts a pd.DataFrame as file_input and can then be passed to DataSet as demonstrated in the [notebooks](https://github.com/MannLabs/alphapeptstats/blob/main/nbs/getting_started.ipynb).

The additional info, like which columns to load still needs to be provided so we can not write a simple wrapper for this.
